name: DartCourse
description: JLG Technology
version: 1.0.0
homepage: https://jlg.technology

environment:
  sdk: '>=2.12.0'
  
dependencies:
  http: ^1.1.0

  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'